<!--install and/or load all R packages-->
```{r setup, include = FALSE, echo = FALSE, warning = FALSE, message = FALSE, fig.align = 'center', out.width = "100%", results = "hide"}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = 'center',
  results = "asis",
  include = TRUE,
  out.width = "100%",
  knitr.kable.NA = '--',
  knitr.table.format = "html"
)
source("Scripts/all-required-packages.R", local = knitr::knit_global())
```

<!--read additional files-->
```{r metrics}
source("Scripts/sjr.R", local = knitr::knit_global())
source("Scripts/citescore.R", local = knitr::knit_global())
source("Scripts/webqualis.R", local = knitr::knit_global())
```

<!--get data-->
```{r metrics-artigos, cache = TRUE, cache.path = "cache/artigos/"}
# read data
sheet.ix <- "PI.completos"
data.sheet <-
  data.frame(read_excel(
    "../PPGCR Unisuam/Produção.xlsx",
    sheet = sheet.ix,
    col_types = c("text")
  ))

# Data cleaning
dois <- as.data.frame(na.omit(data.sheet[, match("DOI", colnames(data.sheet))]))
colnames(dois) <- "DOI"

# cria metadados para rastreio pelo Altmetric
source("Scripts/altmetric-meta-from-dois.R", local = knitr::knit_global())
    
# get metrics from Altmetric and CrossRef
source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())

# store to use downstream
dois_artigos <- dois
doi_unique_artigos <- doi_unique
my_dois_works_artigos <- my_dois_works

# obtain formatted references
formatted_citations <-
  rcrossref::cr_cn(
    c(doi_unique$doi, my_dois_works$doi),
    format = "text",
    raw = TRUE,
    style = "american-medical-association"
  )
formatted_citations <- substring(formatted_citations, 3)
formatted_citations <-
  cbind(seq(1, length(formatted_citations)), formatted_citations)
colnames(formatted_citations) <- c("ID", "Reference")

references_artigos <- formatted_citations
```

<!--get data-->
```{r metrics-resumos, cache = TRUE, cache.path = "cache/resumos/"}
# read data
sheet.ix <- "PI.resumos"
data.sheet <-
  data.frame(read_excel(
    "../PPGCR Unisuam/Produção.xlsx",
    sheet = sheet.ix,
    col_types = c("text")
  ))

# Data cleaning
dois <- as.data.frame(na.omit(data.sheet[, match("DOI", colnames(data.sheet))]))
colnames(dois) <- "DOI"

# cria metadados para rastreio pelo Altmetric
source("Scripts/altmetric-meta-from-dois.R", local = knitr::knit_global())
    
# get metrics from Altmetric and CrossRef
source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())

# store to use downstream
dois_resumos <- dois
doi_unique_resumos <- doi_unique
my_dois_works_resumos <- my_dois_works

# obtain formatted references
formatted_citations <-
  rcrossref::cr_cn(
    c(doi_unique$doi, my_dois_works$doi),
    format = "text",
    raw = TRUE,
    style = "american-medical-association"
  )
formatted_citations <- substring(formatted_citations, 3)
formatted_citations <-
  cbind(seq(1, length(formatted_citations)), formatted_citations)
colnames(formatted_citations) <- c("ID", "Reference")

references_resumos <- formatted_citations
```

<!--get data-->
```{r metrics-preprints, cache = TRUE, cache.path = "cache/preprints/"}
# read data
sheet.ix <- "PI.preprints"
data.sheet <-
  data.frame(read_excel(
    "../PPGCR Unisuam/Produção.xlsx",
    sheet = sheet.ix,
    col_types = c("text")
  ))

# Data cleaning
dois <- as.data.frame(na.omit(data.sheet[, match("DOI", colnames(data.sheet))]))
colnames(dois) <- "DOI"

# cria metadados para rastreio pelo Altmetric
source("Scripts/altmetric-meta-from-dois.R", local = knitr::knit_global())
    
# get metrics from Altmetric and CrossRef
source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())

# store to use downstream
dois_preprints <- dois
doi_unique_preprints <- doi_unique
my_dois_works_preprints <- my_dois_works

# obtain formatted references
formatted_citations <-
  rcrossref::cr_cn(
    c(doi_unique$doi, my_dois_works$doi),
    format = "text",
    raw = TRUE,
    style = "american-medical-association"
  )
formatted_citations <- substring(formatted_citations, 3)
formatted_citations <-
  cbind(seq(1, length(formatted_citations)), formatted_citations)
colnames(formatted_citations) <- c("ID", "Reference")

references_preprints <- formatted_citations
```

<!--get data-->
```{r metrics-livros-capitulos, cache = TRUE, cache.path = "cache/livros_capitulos/"}
# read data
sheet.ix <- "PI.livros"
data.sheet <-
  data.frame(read_excel(
    "../PPGCR Unisuam/Produção.xlsx",
    sheet = sheet.ix,
    col_types = c("text")
  ))

# Data cleaning
dois <- as.data.frame(na.omit(data.sheet[, match("DOI", colnames(data.sheet))]))
colnames(dois) <- "DOI"

# cria metadados para rastreio pelo Altmetric
source("Scripts/altmetric-meta-from-dois.R", local = knitr::knit_global())
    
# get metrics from Altmetric and CrossRef
source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())

# store to use downstream
dois_livros_capitulos <- dois
doi_unique_livros_capitulos <- doi_unique
my_dois_works_livros_capitulos <- my_dois_works

# obtain formatted references
formatted_citations <-
  rcrossref::cr_cn(
    c(doi_unique$doi, my_dois_works$doi),
    format = "text",
    raw = TRUE,
    style = "american-medical-association"
  )
formatted_citations <- substring(formatted_citations, 3)
formatted_citations <-
  cbind(seq(1, length(formatted_citations)), formatted_citations)
colnames(formatted_citations) <- c("ID", "Reference")

references_livros_capitulos <- formatted_citations
```

<!--get data-->
```{r metrics-eventos, cache = TRUE, cache.path = "cache/eventos/"}
# read data
sheet.ix <- "PI.eventos"
data.sheet <-
  data.frame(read_excel(
    "../PPGCR Unisuam/Produção.xlsx",
    sheet = sheet.ix,
    col_types = c("text")
  ))

# Data cleaning
dois <- as.data.frame(na.omit(data.sheet[, match("DOI", colnames(data.sheet))]))
colnames(dois) <- "DOI"

# cria metadados para rastreio pelo Altmetric
source("Scripts/altmetric-meta-from-dois.R", local = knitr::knit_global())
    
# get metrics from Altmetric and CrossRef
source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())

# store to use downstream
dois_eventos <- dois
doi_unique_eventos <- doi_unique
my_dois_works_eventos <- my_dois_works

# obtain formatted references
formatted_citations <-
  rcrossref::cr_cn(
    c(doi_unique$doi, my_dois_works$doi),
    format = "text",
    raw = TRUE,
    style = "american-medical-association"
  )
formatted_citations <- substring(formatted_citations, 3)
formatted_citations <-
  cbind(seq(1, length(formatted_citations)), formatted_citations)
colnames(formatted_citations) <- c("ID", "Reference")

references_eventos <- formatted_citations
```
