<br>
<br>
<br>

# **Downloads**

<br>

## **Documentos vigentes**

<!--script for generating HORIZONTAL LINE-->
<hr style="height:2px;border-width:0;color:gray;background-color:gray">

<br>

<!-- ## Setup for chunk codes -->
```{r echo = FALSE, results = "asis"}
# read packages
library(knitr)
library(readxl)

# read separate sheets
vigentes.raw <- read_excel("../PPGCR Unisuam/Documentos.xlsx", sheet = "Vigentes", col_types = c("text"))

# replace the link by a tag
for(i in 1:dim(vigentes.raw)[1]){
  vigentes.raw[i,3] <- paste("[Baixar](", vigentes.raw[i,3], ")", sep = "")
}

# print table
kable(vigentes.raw)
```

<br>
<br>

## **Documentos revogados**

<!--script for generating HORIZONTAL LINE-->
<hr style="height:2px;border-width:0;color:gray;background-color:gray">

<br>

<!-- ## Setup for chunk codes -->
```{r echo = FALSE, results = "asis"}
# read packages
library(knitr)
library(readxl)

# read separate sheets
revogados.raw <- read_excel("../PPGCR Unisuam/Documentos.xlsx", sheet = "Revogados", col_types = c("text"))

# replace the link by a tag
for(i in 1:dim(vigentes.raw)[1]){
  vigentes.raw[i,3] <- paste("[Baixar](", vigentes.raw[i,3], ")", sep = "")
}

# replace the link by a tag
for(i in 1:dim(revogados.raw)[1]){
  revogados.raw[i,3] <- paste("[Baixar](", revogados.raw[i,3], ")", sep = "")
}

# print table
kable(revogados.raw)
```

<br>
<br>
